### ISSUE TITLE
ImportError: attempted relative import beyond top-level package

### ISSUE THREAD

**Issue by BlackHC** [dholzmueller/bmdal_reg#2]
Hello,

I've tried running `examples/using_bmdal.ipynb`, and I get the following error message in JupyterLab:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[5], line 1
----> 1 from bmdal.feature_data import TensorFeatureData
      2 from bmdal.algorithms import select_batch
      4 train_data = TensorFeatureData(x_train)

File ~/PycharmProjects/bmdal_reg/bmdal/feature_data.py:6
      2 import torch
      4 print(__name__)
----> 6 from .. import utils
      9 def torch_cat(tensors: List[torch.Tensor], dim: int):
     10     """
     11     Implements torch.cat() but doesn't copy if only one tensor is provided.
     12     This can make it faster if no copying behavior is needed.
   (...)
     15     :return: The concatendated tensor.
     16     """

ImportError: attempted relative import beyond top-level package
```

I have tried changing the sys.path etc but to no avail.

Thanks,
 Andreas

**Comment by BlackHC** [comment]
Executing e.g. `python3 download_data.py` does not work either.

I think it's because the repository is at the package's source level and where setup.py would usually be.

**Comment by dholzmueller** [comment]
Thank you, this was a bit messy from rewriting the imports for the PyPI export. I moved all the library python files to a bmdal_reg subfolder now, kept the executable python files at the top level and updated the Jupyter notebooks. I hope it works now.

**Comment by BlackHC** [comment]
Perfect! Just tried this on a vanilla checkout and works perfectly now. Thanks for your patience and for fixing it!
