### ISSUE TITLE
The Issue of Network Architecture Selection

### ISSUE THREAD

**Issue by siwuxei** [dholzmueller/bmdal_reg#4]
Thank you for the work you shared. Recently I carefully tested and read the source code, and the test results met expectations.

But there is a problem here. I use [bmdal_reg](https://github.com/dholzmueller/bmdal_reg) to do regression problems. Can I only choose the ANN architecture? Is it suitable for CNN or RNN related network structures?

Looking forward to your reply!

**Comment by dholzmueller** [comment]
You have multiple options:
- Using the high-level functionality in `bmdal.algorithms.select_batch()` that automatically extracts features from your NN: By default, this only supports linear layers. If your NN architecture has at least one linear layer (preferably at the end), the code can extract features from the linear layers and that might already be good enough. It is also possible to specify methods for extracting features from other layer types in `select_batch()` though it is probably not trivial to come up with a good way to do so. Using `select_batch()` also requires you to specify your dataset as a `TensorFeatureData` object, which might or might not easily work for other types of data.
- Writing your own code to extract features (e.g. just the last-layer input, perhaps averaged over spatial or time dimensions). Then, you can put the features tensor in a `TensorFeatureData` object, create an `IdentityFeatureMap`, put the two together in a `Features` object and then apply one of the selection methods from `bmdal.selection` as shown at the end of https://github.com/dholzmueller/bmdal_reg/blob/main/examples/framework_details.ipynb

**Comment by siwuxei** [comment]
> You have multiple options:
> 
> * Using the high-level functionality in `bmdal.algorithms.select_batch()` that automatically extracts features from your NN: By default, this only supports linear layers. If your NN architecture has at least one linear layer (preferably at the end), the code can extract features from the linear layers and that might already be good enough. It is also possible to specify methods for extracting features from other layer types in `select_batch()` though it is probably not trivial to come up with a good way to do so. Using `select_batch()` also requires you to specify your dataset as a `TensorFeatureData` object, which might or might not easily work for other types of data.
> * Writing your own code to extract features (e.g. just the last-layer input, perhaps averaged over spatial or time dimensions). Then, you can put the features tensor in a `TensorFeatureData` object, create an `IdentityFeatureMap`, put the two together in a `Features` object and then apply one of the selection methods from `bmdal.selection` as shown at the end of https://github.com/dholzmueller/bmdal_reg/blob/main/examples/framework_details.ipynb

Thanks for the reply, as I envisioned, I will try them.
