### ISSUE TITLE
Input shape issue

### ISSUE THREAD

**Issue by alescrnjar** [dholzmueller/bmdal_reg#6]
Hi,
I am writing to report an issue in /bmdal_reg/bmdal_reg/bmdal/feature_data.py: at line 324:

`super().__init__(n_samples=data.shape[-2], device=data.device, dtype=data.dtype)
`

I believe it should be data.shape[0], otherwise the whole method only works for inputs that have shape (batch_size, L1) but cannot work for cases such as (batch_size, L1, L2, ...). Hope I helped you catch a bug!
Best,
Alessandro

**Comment by dholzmueller** [comment]
Thank you, good catch. I uploaded a fix.
